module.exports = {
    dashboard: require('#routes/dashboard'),
    account: require('#routes/account'),
    timetable: require('#routes/timetable'),
    course_overview: require('#routes/course_overview'),
    study_progress: require('#routes/study_progress'),
    announcements: require('#routes/announcements'),
    brightspace: require('#routes/brightspace'),
    sis: require('#routes/sis'),
    mail: require('#routes/mail'),
    events: require('#routes/events'),
    teamsites: require('#routes/teamsites'),
    az_list: require('#routes/a-z_list'),
    staff: require('#routes/staff'),
    locations: require('#routes/locations'),
    library: require('#routes/library'),
    studies: require('#routes/studies'),
    hva_organisation: require('#routes/hva_organisation'),
    help: require('#routes/help'),
}